# Generated by Django 2.2.2 on 2019-06-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewstat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comenter_name', models.TextField()),
                ('service_rating', models.TextField()),
                ('comment_head', models.TextField()),
                ('comment_content', models.TextField()),
            ],
        ),
    ]
