# Generated by Django 2.2.2 on 2019-06-13 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewstat', '0002_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='mistri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mistri_name', models.TextField()),
                ('mistri_img', models.TextField()),
                ('mistri_catagory', models.TextField()),
                ('mistri_address', models.TextField()),
                ('mistri_experiece', models.TextField()),
                ('mistri_job_completed', models.TextField()),
                ('mistri_rating', models.TextField()),
                ('mistri_status', models.TextField()),
                ('mistri_time_available', models.TextField()),
            ],
        ),
    ]
