# Generated by Django 2.2.2 on 2019-06-19 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewstat', '0003_mistri'),
    ]

    operations = [
        migrations.AddField(
            model_name='mistri',
            name='mistr_total_benifit',
            field=models.TextField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mistri',
            name='mistri_Contact',
            field=models.TextField(default='123'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mistri',
            name='mistri_amount_to_paid',
            field=models.TextField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mistri',
            name='mistri_fee',
            field=models.TextField(default='123'),
            preserve_default=False,
        ),
    ]
