# Generated by Django 2.2.2 on 2019-06-20 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewstat', '0004_auto_20190619_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mistri',
            name='mistr_total_benifit',
        ),
        migrations.RemoveField(
            model_name='mistri',
            name='mistri_Contact',
        ),
        migrations.RemoveField(
            model_name='mistri',
            name='mistri_amount_to_paid',
        ),
        migrations.RemoveField(
            model_name='mistri',
            name='mistri_time_available',
        ),
        migrations.AddField(
            model_name='mistri',
            name='mistri_benifit',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mistri',
            name='mistri_contact_number',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mistri',
            name='mistri_job_assigned_date',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mistri',
            name='mistri_job_finishing_date',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mistri',
            name='mistri_money_to_be_paid',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mistri',
            name='mistri_special_ability',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='mistri',
            name='mistri_address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='mistri',
            name='mistri_catagory',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='mistri',
            name='mistri_experiece',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='mistri',
            name='mistri_fee',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='mistri',
            name='mistri_img',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='mistri',
            name='mistri_job_completed',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='mistri',
            name='mistri_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='mistri',
            name='mistri_rating',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='mistri',
            name='mistri_status',
            field=models.TextField(null=True),
        ),
    ]
